# Generated by Django 4.1.9 on 2023-07-20 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(default='', max_length=255, null=True)),
                ('invoice_no', models.IntegerField(default=0)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=500, null=True)),
                ('quantity', models.PositiveIntegerField(default=0, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='home.invoice')),
            ],
        ),
    ]
